### Singular Value Decomposition and Classification

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD
import seaborn as sb

In [3]:
columns=['userid','item_id','rating','timestamp']
frame=pd.read_csv('ml-100k/u.data',sep='\t',names=columns)
frame.head()

   userid  item_id  rating  timestamp
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [19]:
columns=['item_id','movie title','release date','video release date','IMDB URL','unknown','Action','Adventure','Animation'
       ,'Children','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi'
       ,'Thriller','War','Western']
movies=pd.read_csv('ml-100k/u.item',sep='|',names=columns,encoding='latin-1')
movies.head(50)

,item_id,movie title,release date,video release date,IMDB URL,unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,01-Jan-1995,NaN,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,Twelve Monkeys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Twelve%20Monk...,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,8,Babe (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Babe%20(1995),0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,9,Dead Man Walking (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Dead%20Man%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,Richard III (1995),22-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Richard%20III...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,11,Seven (Se7en) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Se7en%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,12,"Usual Suspects, The (1995)",14-Aug-1995,NaN,http://us.imdb.com/M/title-exact?Usual%20Suspe...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,13,Mighty Aphrodite (1995),30-Oct-1995,NaN,http://us.imdb.com/M/title-exact?Mighty%20Aphr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,14,"Postino, Il (1994)",01-Jan-1994,NaN,"http://us.imdb.com/M/title-exact?Postino,%20Il...",0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,15,Mr. Holland's Opus (1995),29-Jan-1996,NaN,http://us.imdb.com/M/title-exact?Mr.%20Holland...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,16,French Twist (Gazon maudit) (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Gazon%20maudi...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
16,17,From Dusk Till Dawn (1996),05-Feb-1996,NaN,http://us.imdb.com/M/title-exact?From%20Dusk%2...,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
17,18,"White Balloon, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Badkonake%20S...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,19,Antonia's Line (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Antonia%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,20,Angels and Insects (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Angels%20and%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
20,21,Muppet Treasure Island (1996),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Muppet%20Trea...,0,1,1,0,0,...,0,0,0,1,0,0,0,1,0,0
21,22,Braveheart (1995),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Braveheart%20...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,23,Taxi Driver (1976),16-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Taxi%20Driver...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,24,Rumble in the Bronx (1995),23-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Hong%20Faan%2...,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24,25,"Birdcage, The (1996)",08-Mar-1996,NaN,"http://us.imdb.com/M/title-exact?Birdcage,%20T...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,26,"Brothers McMullen, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Brothers%20Mc...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,27,Bad Boys (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Bad%20Boys%20...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,28,Apollo 13 (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Apollo%2013%2...,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,29,Batman Forever (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Batman%20Fore...,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
29,30,Belle de jour (1967),01-Jan-1967,NaN,http://us.imdb.com/M/title-exact?Belle%20de%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,31,Crimson Tide (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Crimson%20Tid...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
31,32,Crumb (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Crumb%20(1994),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,33,Desperado (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Desperado%20(...,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
33,34,"Doom Generation, The (1995)",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Doom%20Genera...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,35,Free Willy 2: The Adventure Home (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Free%20Willy%...,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
35,36,Mad Love (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mad%20Love%20...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
36,37,Nadja (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Nadja%20(1994),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,38,"Net, The (1995)",01-Jan-1995,NaN,"http://us.imdb.com/M/title-exact?Net,%20The%20...",0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
38,39,Strange Days (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Strange%20Day...,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
39,40,"To Wong Foo, Thanks for Everything! Julie Newm...",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?To%20Wong%20F...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,41,Billy Madison (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Billy%20Madis...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,42,Clerks (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Clerks%20(1994),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,43,Disclosure (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Disclosure%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
43,44,Dolores Claiborne (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Dolores%20Cla...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
44,45,Eat Drink Man Woman (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Yinshi%20Nan%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,46,Exotica (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Exotica%20(1994),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,47,Ed Wood (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Ed%20Wood%20(...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,48,Hoop Dreams (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Hoop%20Dreams...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,49,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
49,50,Star Wars (1977),01-Jan-1977,NaN,http://us.imdb.com/M/title-exact?Star%20Wars%2...,0,1,1,0,0,...,0,0,0,0,0,1,1,0,1,0

In [7]:
#number of records present
len(movies)

1682

In [9]:
combined_movies_data=pd.merge(frame,movies ,on='item_id')
combined_movies_data.head()

,userid,item_id,rating,timestamp,movie title,release date,video release date,IMDB URL,unknown,Action,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,196,242,3,881250949,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0
1,63,242,3,875747190,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0
2,226,242,5,883888671,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0
3,154,242,3,879138235,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0
4,306,242,5,876503793,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
combined_movies_data.groupby('item_id')['rating'].count().sort_values(ascending=False).head()

item_id
50     583
258    509
100    508
181    507
294    485
Name: rating, dtype: int64

In [18]:
pd.set_option('display.max_rows',100)

0       http://us.imdb.com/M/title-exact?Toy%20Story%2...
1       http://us.imdb.com/M/title-exact?GoldenEye%20(...
2       http://us.imdb.com/M/title-exact?Four%20Rooms%...
3       http://us.imdb.com/M/title-exact?Get%20Shorty%...
4       http://us.imdb.com/M/title-exact?Copycat%20(1995)
                              ...
1677    http://us.imdb.com/M/title-exact?Mat%27+i+syn+...
1678    http://us.imdb.com/M/title-exact?B%2E+Monkey+(...
1679        http://us.imdb.com/Title?Sliding+Doors+(1998)
1680    http://us.imdb.com/M/title-exact?You%20So%20Cr...
1681    http://us.imdb.com/M/title-exact?Schrei%20aus%...
Name: IMDB URL, Length: 1682, dtype: object

In [23]:
Filter=combined_movies_data['item_id']==50
combined_movies_data[Filter]['movie title'].unique()

array(['Star Wars (1977)'], dtype=object)

In [24]:
#building a uitility matrix
rating_cross_tab=combined_movies_data.pivot_table(values='rating',index='userid',columns='movie title',fill_value=0)
rating_cross_tab

movie title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
userid,,,,,,,,,,,,,,,,,,,,,
1,0,0,2,5,0,0,3,4,0,0,...,0,0,0,5,3,0,0,0,4,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,2,0,0,0,0,4,0,0,...,0,0,0,4,0,0,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
941,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
942,0,0,0,0,0,0,0,3,0,3,...,0,0,0,0,0,0,0,0,0,0
943,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,4,3,0,0,0,0

In [29]:
#creating a Transpose of the matrix
x=rating_cross_tab.values.T
x.shape

(1664, 943)

In [36]:
svd=TruncatedSVD(n_components=12,random_state=17)
resultant_matrix=svd.fit_transform(x)
resultant_matrix.shape

(1664, 12)

### generating co-relation matrix

In [34]:
corr_mat=np.corrcoef(resultant_matrix)
corr_mat.shape

(1664, 1664)

In [46]:
movies_names=rating_cross_tab.columns
movies_list=list(movies_names)
star_war=movies_list.index('Star Wars (1977)')

(1664,)

In [45]:
corr_star_wars=corr_mat[star_war]
corr_star_wars

array([0.36854685, 0.42380505, 0.59468319, ..., 0.33301726, 0.64177278,
       0.26805079])

### recommending movies that are co-related

In [65]:

arr=list(movies_names[(corr_star_wars<1.0) & (corr_star_wars >0.9)])
arr

['Die Hard (1988)',
 'Empire Strikes Back, The (1980)',
 'Fugitive, The (1993)',
 'Raiders of the Lost Ark (1981)',
 'Return of the Jedi (1983)',
 'Terminator 2: Judgment Day (1991)',
 'Terminator, The (1984)',
 'Toy Story (1995)']

In [66]:
arr=list(movies_names[(corr_star_wars<1.0) & (corr_star_wars >0.95)])
arr

['Return of the Jedi (1983)']